export const EVENT = {
  WINDOW_CLOSE: 'WINDOW_CLOSE',
  WINDOW_RESIZ: 'WINDOW_RESIZ',
  WINDOW_MIN: 'WINDOW_MIN',
  LOGIN: 'LOGIN',
  LOGIN_CLOSE: 'LOGIN_CLOSE',
  RELOAD_USER: 'RELOAD_USER',
  SEND: 'SEND',
};
