@baseUrl=http://localhost:35011
@Cookie=MUSIC_U=3449ae18ea9eaa5920f4b0623c5af8c69c6313aee1f9d7a604a9ec2fcbc608b3993166e004087dd3b309af8c478a4abf2461c5ad02bf4d0d4bc417e7cf32b3a555ecebd66669c36ca0d2166338885bd7


### hot search
GET {{baseUrl}}/search/hot HTTP/1.1
Cookie: {{Cookie}}


### hot search detail
GET {{baseUrl}}/search/hot/detail HTTP/1.1
Cookie: {{Cookie}}

### hot search suggest
GET {{baseUrl}}/search/suggest?keywords=不 HTTP/1.1
### hot search suggest
GET {{baseUrl}}/search/suggest?keywords=不&type=mobile HTTP/1.1
Cookie: {{Cookie}}
###  search multimatch
GET {{baseUrl}}/search/multimatch?keywords=不 HTTP/1.1
Cookie: {{Cookie}}
###  search
GET {{baseUrl}}/search?keywords=不&limit=10 HTTP/1.1
Cookie: {{Cookie}}
###  search
GET {{baseUrl}}/cloudsearch?keywords=不&limit=10 HTTP/1.1
Cookie: {{Cookie}}